### PR TITLE
Information about Tomcat8x added into README.

### PR DESCRIPTION
**Pull request by bura**

### CODE REVIEW

**Comment by mkornipati** [comment]
@bura, @bmuschko, Just check if we go the fix available for the  issue reported above - Taglibs that provide the TLD as part of their JAR in a META-INF directory?

**Comment by bmuschko** [comment]
@mkornipati Can you clarify? I don't understand the question.

**Comment by mkornipati** [comment]
@bmuschko, Just checking if the fix for the issue mentioned by you on oct 11th 2014 is been fixed..
___________
*@bura Thanks for checking. This issue still happens if you are using Taglibs that provide the TLD as part of their JAR in a META-INF directory. This should be resolved automatically without having to create a TLD file in your web app. One example is Sitemesh 2.4.2. Would you mind looking into that as well?*
______________

**Comment by bmuschko** [comment]
I manually made the changes to README file. Thanks again for initially working on it!

**Pull request closed without merging**
