### PR TITLE
Feature/add cacheSize config, fix tomcat log cache warning.

### PR DESCRIPTION
**Pull request by xingxiuyi**
some jar like vaadin, contains java source file and other resources file. Tomcat will log warning for each file.

solve this problem: add `cacheSize ` config.

FIX: #170

### CODE REVIEW

**Comment by xingxiuyi** [comment]
only support tomcat 8+

use cacheSize property, tomcat 6 & tomcat 7 will print a warning.

**Comment by xingxiuyi** [comment]
OK

please wait a few days.

**Comment by bmuschko** [comment]
@xingxiuyi Are you still interested in finishing off this pull request?

**Comment by xingxiuyi** [comment]
@bmuschko I'm sorry, my work was too busy before. I will finish the pull_request as soon as possible.

**Comment by bmuschko** [comment]
@xingxiuyi Is this still happening? Otherwise I am going to close this PR for now.

**Comment by bmuschko** [comment]
Closing this pull request as new test has been provided. Please let me know if you'd like to continue adding one in which case we can reopen the pull request.

**Pull request closed without merging**
