### PR TITLE
Fix for #147: Updated to allow external xml entities in web.xml.

### PR DESCRIPTION
**Pull request by scottresnik**
This fixes issue #147.  I'm not really well versed with tests for gradle plugins, so I didn't create one for this case.

### CODE REVIEW

**Comment by bmuschko** [comment]
The attribute `blockexternal` should become a input property (including the corresponding annotation) and should have the default value `false`. Please also add functional tests to `TomcatJasperFunctionalTest.groovy` that demonstrates the expected behavior for this property. I won't merge the PR without appropriate test coverage.

**Comment by bmuschko** [comment]
Are you still interested in the functionality? Please provide the requested changes. Otherwise I won't merge.

**Comment by bmuschko** [comment]
I am sorry but I can't merge the change without any tests. Feel free to reopen if you'd like to continue to work on this PR.

**Comment by scottresnik** [comment]
I am in agreement.  This functionality is no longer needed.

**Pull request closed without merging**
