### PR TITLE
add feature to configure values and realm

### PR DESCRIPTION
**Pull request by bdbogjoe**
in my app i need to customize valves and realm used by container

### CODE REVIEW

**Comment by bmuschko** [comment]
Thanks for providing the pull request. I am going to run through a full review soon. In the meantime could I ask you to remove three things from the code changes?

1. Changes to the code formatting. Reason: Makes it much easier to review the change.
2. Upgrade of the Gradle Wrapper and its scripts. Reason: Might introduce additional changes that are not necessary for the functionality.
3. Author information in Javadocs. Reason: I am going to remove all of them from the Javadocs soon. This is already reflected in the commit history.

**Comment by bmuschko** [comment]
@bdbogjoe Are you still planning to touch up your PR based on my comments? I don't think it will merge the changes as is.

**Comment by bdbogjoe** [comment]
Hi I understand your point, but I need to revert all and start it from scratch because difficult to revert the formatting.
But yes I will try to find some time to review my PR

**Comment by bmuschko** [comment]
@bdbogjoe Sounds good.

**Comment by bmuschko** [comment]
@bdbogjoe I didn't see any traction on this pull request in the meantime. I am going to close this for now. Feel free to open a new PR or push to this one to revive.

**Comment by bdbogjoe** [comment]
sorry for that, i'm very busy at office these last days, but for sure will review it.
I will start from scratch from current master branch.

**Pull request closed without merging**
