### PR TITLE
Fix for "JasperInitializer in tomcat 8 embedded mode #132"

### PR DESCRIPTION
**Pull request by mkornipati**
Hi @bmuschko, As we discussed, here is the proposed fix for https://github.com/bmuschko/gradle-tomcat-plugin/issues/132

### CODE REVIEW

**Comment by bmuschko** [comment]
Thanks for the pull request. It has been merged.

**Comment by mkornipati** [comment]
Thanks @bmuschko . Do you have any plans to release this very near future,may be part of 2.2.3?

Regards,
Mohan

**Comment by bmuschko** [comment]
Released.

**Comment by mkornipati** [comment]
Thanks @bmuschko

**Pull request merged**
